cxx_binary(
  name = 'client',
  srcs = [
    'EchoClient.cpp',
  ],
  deps = [
    '//:wangle',
  ],
)

cxx_binary(
  name = 'server',
  srcs = [
    'EchoServer.cpp',
  ],
  deps = [
    '//:wangle',
  ],
)
